apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: 806307902094.dkr.ecr.us-east-1.amazonaws.com/clo835-assign-app:v0.1
        env:
        - name: DBHOST
          value: "mysql.mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        ports:
        - containerPort: 8080